# Generated by Django 4.2 on 2023-06-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='prebook',
            field=models.BooleanField(default=False),
        ),
    ]
